version: '3'

tasks:
  generate-client:
    desc: Generate Go clients for each OpenAPI spec file
    cmds:
      - |
        for spec in hack/specs/*_API_Spec.yaml; do
          package_name=$(basename "$spec" _API_Spec.yaml | sed 's/_//g' | sed 's/\./_/g' )
          package_name_lower=$(echo "$package_name" | tr '[:upper:]' '[:lower:]')
          echo "Generating client for $spec with package name $package_name"
          mkdir -p "pkg/pingdom/client/${package_name_lower}"
          oapi-codegen --package="${package_name_lower}" --generate=client,types "$spec" > "pkg/pingdom/client/${package_name_lower}/${package_name}.go"
        done
    silent: false
  generate:
    desc: generate openapi client with openapi generator
    cmds:
     - |
        docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
        -i /local/hack/API_3.1.yaml \
        -g go \
        -o /local/pkg/pingdom/openapi
  replace-github-repo:
    desc: set github repo name in generated files
    cmds: 
      - |
        git_user_repo="github.com/karlderkaefer/pingdom-golang-client/pkg/pingdom/openapi"
        find ./pkg/pingdom/openapi -type f -exec sed -i "" "s|github.com/GIT_USER_ID/GIT_REPO_ID|$git_user_repo|g" {} \;
