// Package credits provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package credits

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreditsRespAttrs defines model for credits_resp_attrs.
type CreditsRespAttrs struct {
	Credits *struct {
		// Autofillsms Auto fill SMS
		Autofillsms *bool `json:"autofillsms,omitempty"`

		// AutofillsmsAmount The amount of sms to purchase when "autofillsms_when_left" is triggered
		AutofillsmsAmount *int `json:"autofillsms_amount,omitempty"`

		// AutofillsmsWhenLeft The amount of sms left that is going to trigger purchase of sms
		AutofillsmsWhenLeft *int `json:"autofillsms_when_left,omitempty"`

		// Availablechecks Free check slots available for new checks
		Availablechecks *int `json:"availablechecks,omitempty"`

		// Availablerumsites Open RUM site slots available
		Availablerumsites *int `json:"availablerumsites,omitempty"`

		// Availablesms SMS credits remaining on this account
		Availablesms *int `json:"availablesms,omitempty"`

		// Availablesmstests SMS provider tests remaining on this account
		Availablesmstests *int `json:"availablesmstests,omitempty"`

		// Checklimit Total number of check slots on this account
		Checklimit *int `json:"checklimit,omitempty"`

		// MaxSmsOverage The amount of overage SMSes that may be used, or null if SMS overage is not enabled.
		MaxSmsOverage *int `json:"max_sms_overage,omitempty"`

		// Maxrumfilters Number of maximum rum filters
		Maxrumfilters *int `json:"maxrumfilters,omitempty"`

		// Maxrumpageviews Number of maximum pageviews per month
		Maxrumpageviews *int `json:"maxrumpageviews,omitempty"`

		// Useddefault Total number of default check slots
		Useddefault *int `json:"useddefault,omitempty"`

		// Usedrumsites Number of used RUM sites
		Usedrumsites *int `json:"usedrumsites,omitempty"`

		// Usedtransaction Total number of transaction check slots
		Usedtransaction *int `json:"usedtransaction,omitempty"`
	} `json:"credits,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCredits request
	GetCredits(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCredits(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCreditsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCreditsRequest generates requests for GetCredits
func NewGetCreditsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/credits")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCreditsWithResponse request
	GetCreditsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCreditsResponse, error)
}

type GetCreditsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreditsRespAttrs
}

// Status returns HTTPResponse.Status
func (r GetCreditsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCreditsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCreditsWithResponse request returning *GetCreditsResponse
func (c *ClientWithResponses) GetCreditsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCreditsResponse, error) {
	rsp, err := c.GetCredits(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCreditsResponse(rsp)
}

// ParseGetCreditsResponse parses an HTTP response from a GetCreditsWithResponse call
func ParseGetCreditsResponse(rsp *http.Response) (*GetCreditsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCreditsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreditsRespAttrs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
