// Package summary_average provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package summary_average

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// SummaryAverageBycountry defines model for summary.average_bycountry.
type SummaryAverageBycountry = bool

// SummaryAverageByprobe defines model for summary.average_byprobe.
type SummaryAverageByprobe = bool

// SummaryAverageCheckid defines model for summary.average_checkid.
type SummaryAverageCheckid = int

// SummaryAverageFrom defines model for summary.average_from.
type SummaryAverageFrom = int

// SummaryAverageIncludeuptime defines model for summary.average_includeuptime.
type SummaryAverageIncludeuptime = bool

// SummaryAverageProbes defines model for summary.average_probes.
type SummaryAverageProbes = string

// SummaryAverageTo defines model for summary.average_to.
type SummaryAverageTo = int

// SummaryRespAttrs defines model for summary_resp_attrs.
type SummaryRespAttrs struct {
	Summary *struct {
		Responsetime *struct {
			Avgresponse *SummaryRespAttrs_Summary_Responsetime_Avgresponse `json:"avgresponse,omitempty"`

			// From Start time of period
			From *float32 `json:"from,omitempty"`

			// To End time of period
			To *float32 `json:"to,omitempty"`
		} `json:"responsetime,omitempty"`
		Status *struct {
			// Totaldown Total downtime in seconds (Please note that the accuracy of this value is depending on your check resolution).
			Totaldown *int `json:"totaldown,omitempty"`

			// Totalunknown Total unknown/unmonitored/paused in seconds (Please note that the accuracy of this value is depending on your check resolution. Also note that time before the check was created counts as unknown).
			Totalunknown *int `json:"totalunknown,omitempty"`

			// Totalup Total uptime in seconds (Please note that the accuracy of this value is depending on your check resolution).
			Totalup *int `json:"totalup,omitempty"`
		} `json:"status,omitempty"`
	} `json:"summary,omitempty"`
}

// SummaryRespAttrsSummaryResponsetimeAvgresponse0 Total average response time in milliseconds
type SummaryRespAttrsSummaryResponsetimeAvgresponse0 = int

// SummaryRespAttrsSummaryResponsetimeAvgresponse1 defines model for .
type SummaryRespAttrsSummaryResponsetimeAvgresponse1 = []struct {
	// Avgresponse Group average response time in milliseconds
	Avgresponse *int `json:"avgresponse,omitempty"`

	// Countryiso Country group ISO code
	Countryiso *string `json:"countryiso,omitempty"`

	// Probeid Probe group probe identifier
	Probeid *int `json:"probeid,omitempty"`
}

// SummaryRespAttrs_Summary_Responsetime_Avgresponse defines model for SummaryRespAttrs.Summary.Responsetime.Avgresponse.
type SummaryRespAttrs_Summary_Responsetime_Avgresponse struct {
	union json.RawMessage
}

// GetSummaryAverageCheckidParams defines parameters for GetSummaryAverageCheckid.
type GetSummaryAverageCheckidParams struct {
	// From Start time of period. Format is UNIX timestamp
	From *SummaryAverageFrom `form:"from,omitempty" json:"from,omitempty"`

	// To End time of period. Format is UNIX timestamp. Default is the current time
	To *SummaryAverageTo `form:"to,omitempty" json:"to,omitempty"`

	// Probes Filter to only use results from a list of probes. Format is a comma separated list of probe identifiers. By default result from all probes are shown.
	Probes *SummaryAverageProbes `form:"probes,omitempty" json:"probes,omitempty"`

	// Includeuptime Include uptime information
	Includeuptime *SummaryAverageIncludeuptime `form:"includeuptime,omitempty" json:"includeuptime,omitempty"`

	// Bycountry Split response times into country groups
	Bycountry *SummaryAverageBycountry `form:"bycountry,omitempty" json:"bycountry,omitempty"`

	// Byprobe Split response times into probe groups
	Byprobe *SummaryAverageByprobe `form:"byprobe,omitempty" json:"byprobe,omitempty"`
}

// AsSummaryRespAttrsSummaryResponsetimeAvgresponse0 returns the union data inside the SummaryRespAttrs_Summary_Responsetime_Avgresponse as a SummaryRespAttrsSummaryResponsetimeAvgresponse0
func (t SummaryRespAttrs_Summary_Responsetime_Avgresponse) AsSummaryRespAttrsSummaryResponsetimeAvgresponse0() (SummaryRespAttrsSummaryResponsetimeAvgresponse0, error) {
	var body SummaryRespAttrsSummaryResponsetimeAvgresponse0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSummaryRespAttrsSummaryResponsetimeAvgresponse0 overwrites any union data inside the SummaryRespAttrs_Summary_Responsetime_Avgresponse as the provided SummaryRespAttrsSummaryResponsetimeAvgresponse0
func (t *SummaryRespAttrs_Summary_Responsetime_Avgresponse) FromSummaryRespAttrsSummaryResponsetimeAvgresponse0(v SummaryRespAttrsSummaryResponsetimeAvgresponse0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSummaryRespAttrsSummaryResponsetimeAvgresponse0 performs a merge with any union data inside the SummaryRespAttrs_Summary_Responsetime_Avgresponse, using the provided SummaryRespAttrsSummaryResponsetimeAvgresponse0
func (t *SummaryRespAttrs_Summary_Responsetime_Avgresponse) MergeSummaryRespAttrsSummaryResponsetimeAvgresponse0(v SummaryRespAttrsSummaryResponsetimeAvgresponse0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsSummaryRespAttrsSummaryResponsetimeAvgresponse1 returns the union data inside the SummaryRespAttrs_Summary_Responsetime_Avgresponse as a SummaryRespAttrsSummaryResponsetimeAvgresponse1
func (t SummaryRespAttrs_Summary_Responsetime_Avgresponse) AsSummaryRespAttrsSummaryResponsetimeAvgresponse1() (SummaryRespAttrsSummaryResponsetimeAvgresponse1, error) {
	var body SummaryRespAttrsSummaryResponsetimeAvgresponse1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSummaryRespAttrsSummaryResponsetimeAvgresponse1 overwrites any union data inside the SummaryRespAttrs_Summary_Responsetime_Avgresponse as the provided SummaryRespAttrsSummaryResponsetimeAvgresponse1
func (t *SummaryRespAttrs_Summary_Responsetime_Avgresponse) FromSummaryRespAttrsSummaryResponsetimeAvgresponse1(v SummaryRespAttrsSummaryResponsetimeAvgresponse1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSummaryRespAttrsSummaryResponsetimeAvgresponse1 performs a merge with any union data inside the SummaryRespAttrs_Summary_Responsetime_Avgresponse, using the provided SummaryRespAttrsSummaryResponsetimeAvgresponse1
func (t *SummaryRespAttrs_Summary_Responsetime_Avgresponse) MergeSummaryRespAttrsSummaryResponsetimeAvgresponse1(v SummaryRespAttrsSummaryResponsetimeAvgresponse1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t SummaryRespAttrs_Summary_Responsetime_Avgresponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SummaryRespAttrs_Summary_Responsetime_Avgresponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetSummaryAverageCheckid request
	GetSummaryAverageCheckid(ctx context.Context, checkid SummaryAverageCheckid, params *GetSummaryAverageCheckidParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetSummaryAverageCheckid(ctx context.Context, checkid SummaryAverageCheckid, params *GetSummaryAverageCheckidParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSummaryAverageCheckidRequest(c.Server, checkid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetSummaryAverageCheckidRequest generates requests for GetSummaryAverageCheckid
func NewGetSummaryAverageCheckidRequest(server string, checkid SummaryAverageCheckid, params *GetSummaryAverageCheckidParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "checkid", runtime.ParamLocationPath, checkid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/summary.average/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.From != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "from", runtime.ParamLocationQuery, *params.From); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.To != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "to", runtime.ParamLocationQuery, *params.To); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Probes != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "probes", runtime.ParamLocationQuery, *params.Probes); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Includeuptime != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "includeuptime", runtime.ParamLocationQuery, *params.Includeuptime); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Bycountry != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "bycountry", runtime.ParamLocationQuery, *params.Bycountry); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Byprobe != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "byprobe", runtime.ParamLocationQuery, *params.Byprobe); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetSummaryAverageCheckidWithResponse request
	GetSummaryAverageCheckidWithResponse(ctx context.Context, checkid SummaryAverageCheckid, params *GetSummaryAverageCheckidParams, reqEditors ...RequestEditorFn) (*GetSummaryAverageCheckidResponse, error)
}

type GetSummaryAverageCheckidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SummaryRespAttrs
}

// Status returns HTTPResponse.Status
func (r GetSummaryAverageCheckidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSummaryAverageCheckidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetSummaryAverageCheckidWithResponse request returning *GetSummaryAverageCheckidResponse
func (c *ClientWithResponses) GetSummaryAverageCheckidWithResponse(ctx context.Context, checkid SummaryAverageCheckid, params *GetSummaryAverageCheckidParams, reqEditors ...RequestEditorFn) (*GetSummaryAverageCheckidResponse, error) {
	rsp, err := c.GetSummaryAverageCheckid(ctx, checkid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSummaryAverageCheckidResponse(rsp)
}

// ParseGetSummaryAverageCheckidResponse parses an HTTP response from a GetSummaryAverageCheckidWithResponse call
func ParseGetSummaryAverageCheckidResponse(rsp *http.Response) (*GetSummaryAverageCheckidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSummaryAverageCheckidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SummaryRespAttrs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
