// Package summary_outage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package summary_outage

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for SummaryOutageOrder.
const (
	Asc  SummaryOutageOrder = "asc"
	Desc SummaryOutageOrder = "desc"
)

// Defines values for SummaryOutageRespAttrsSummaryStatesStatus.
const (
	Down    SummaryOutageRespAttrsSummaryStatesStatus = "down"
	Unknown SummaryOutageRespAttrsSummaryStatesStatus = "unknown"
	Up      SummaryOutageRespAttrsSummaryStatesStatus = "up"
)

// SummaryOutageCheckid defines model for summary.outage_checkid.
type SummaryOutageCheckid = int

// SummaryOutageFrom defines model for summary.outage_from.
type SummaryOutageFrom = int

// SummaryOutageOrder defines model for summary.outage_order.
type SummaryOutageOrder string

// SummaryOutageRespAttrs defines model for summary.outage_resp_attrs.
type SummaryOutageRespAttrs struct {
	Summary *struct {
		States *[]struct {
			// Status Interval status
			Status *SummaryOutageRespAttrsSummaryStatesStatus `json:"status,omitempty"`

			// Timefrom Interval start. Format UNIX timestamp
			Timefrom *float32 `json:"timefrom,omitempty"`

			// Timeto Interval end. Format UNIX timestamp
			Timeto *float32 `json:"timeto,omitempty"`
		} `json:"states,omitempty"`
	} `json:"summary,omitempty"`
}

// SummaryOutageRespAttrsSummaryStatesStatus Interval status
type SummaryOutageRespAttrsSummaryStatesStatus string

// SummaryOutageTo defines model for summary.outage_to.
type SummaryOutageTo = int

// GetSummaryOutageCheckidParams defines parameters for GetSummaryOutageCheckid.
type GetSummaryOutageCheckidParams struct {
	// From Start time of period. Format is UNIX timestamp. Default value is one week earlier than `to`.
	From *SummaryOutageFrom `form:"from,omitempty" json:"from,omitempty"`

	// To End time of period. Format is UNIX timestamp. Default value is the current time.
	To *SummaryOutageTo `form:"to,omitempty" json:"to,omitempty"`

	// Order Sorting order of outages. Ascending or descending.
	Order *SummaryOutageOrder `form:"order,omitempty" json:"order,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetSummaryOutageCheckid request
	GetSummaryOutageCheckid(ctx context.Context, checkid SummaryOutageCheckid, params *GetSummaryOutageCheckidParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetSummaryOutageCheckid(ctx context.Context, checkid SummaryOutageCheckid, params *GetSummaryOutageCheckidParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSummaryOutageCheckidRequest(c.Server, checkid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetSummaryOutageCheckidRequest generates requests for GetSummaryOutageCheckid
func NewGetSummaryOutageCheckidRequest(server string, checkid SummaryOutageCheckid, params *GetSummaryOutageCheckidParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "checkid", runtime.ParamLocationPath, checkid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/summary.outage/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.From != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "from", runtime.ParamLocationQuery, *params.From); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.To != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "to", runtime.ParamLocationQuery, *params.To); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "order", runtime.ParamLocationQuery, *params.Order); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetSummaryOutageCheckidWithResponse request
	GetSummaryOutageCheckidWithResponse(ctx context.Context, checkid SummaryOutageCheckid, params *GetSummaryOutageCheckidParams, reqEditors ...RequestEditorFn) (*GetSummaryOutageCheckidResponse, error)
}

type GetSummaryOutageCheckidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SummaryOutageRespAttrs
}

// Status returns HTTPResponse.Status
func (r GetSummaryOutageCheckidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSummaryOutageCheckidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetSummaryOutageCheckidWithResponse request returning *GetSummaryOutageCheckidResponse
func (c *ClientWithResponses) GetSummaryOutageCheckidWithResponse(ctx context.Context, checkid SummaryOutageCheckid, params *GetSummaryOutageCheckidParams, reqEditors ...RequestEditorFn) (*GetSummaryOutageCheckidResponse, error) {
	rsp, err := c.GetSummaryOutageCheckid(ctx, checkid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSummaryOutageCheckidResponse(rsp)
}

// ParseGetSummaryOutageCheckidResponse parses an HTTP response from a GetSummaryOutageCheckidWithResponse call
func ParseGetSummaryOutageCheckidResponse(rsp *http.Response) (*GetSummaryOutageCheckidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSummaryOutageCheckidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SummaryOutageRespAttrs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
