// Package probes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package probes

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Probe defines model for Probe.
type Probe struct {
	// Active Is the probe currently active?
	Active  *bool   `json:"active,omitempty"`
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`

	// Countryiso Country ISO code
	Countryiso *string `json:"countryiso,omitempty"`

	// Hostname DNS name
	Hostname *string `json:"hostname,omitempty"`
	Id       *int    `json:"id,omitempty"`

	// Ip IPv4 address
	Ip *string `json:"ip,omitempty"`

	// Ipv6 IPv6 address (not all probes have this)
	Ipv6 *string `json:"ipv6,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Probes defines model for Probes.
type Probes struct {
	Probes *[]Probe `json:"probes,omitempty"`
}

// GetProbesParams defines parameters for GetProbes.
type GetProbesParams struct {
	// Limit Limits the number of returned probes to the specified quantity.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset for listing. (Requires limit.)
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Onlyactive Return only active probes.
	Onlyactive *bool `form:"onlyactive,omitempty" json:"onlyactive,omitempty"`

	// Includedeleted Include old probes that are no longer in use.
	Includedeleted *bool `form:"includedeleted,omitempty" json:"includedeleted,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetProbes request
	GetProbes(ctx context.Context, params *GetProbesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetProbes(ctx context.Context, params *GetProbesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProbesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetProbesRequest generates requests for GetProbes
func NewGetProbesRequest(server string, params *GetProbesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/probes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Onlyactive != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "onlyactive", runtime.ParamLocationQuery, *params.Onlyactive); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Includedeleted != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "includedeleted", runtime.ParamLocationQuery, *params.Includedeleted); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetProbesWithResponse request
	GetProbesWithResponse(ctx context.Context, params *GetProbesParams, reqEditors ...RequestEditorFn) (*GetProbesResponse, error)
}

type GetProbesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Probes
}

// Status returns HTTPResponse.Status
func (r GetProbesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProbesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetProbesWithResponse request returning *GetProbesResponse
func (c *ClientWithResponses) GetProbesWithResponse(ctx context.Context, params *GetProbesParams, reqEditors ...RequestEditorFn) (*GetProbesResponse, error) {
	rsp, err := c.GetProbes(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProbesResponse(rsp)
}

// ParseGetProbesResponse parses an HTTP response from a GetProbesWithResponse call
func ParseGetProbesResponse(rsp *http.Response) (*GetProbesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProbesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Probes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
