// Package reference provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package reference

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Country defines model for Country.
type Country struct {
	// Id Country id
	Id *int `json:"id,omitempty"`

	// Iso Country ISO code
	Iso *string `json:"iso,omitempty"`

	// Name Country name
	Name *string `json:"name,omitempty"`
}

// DateTimeFormat defines model for DateTimeFormat.
type DateTimeFormat struct {
	// Description Date/time description
	Description *string `json:"description,omitempty"`

	// Id Date/time identifier
	Id *int `json:"id,omitempty"`
}

// NumberFormat defines model for NumberFormat.
type NumberFormat struct {
	// Description Number format description
	Description *string `json:"description,omitempty"`

	// Id Number format identifier
	Id *int `json:"id,omitempty"`
}

// PhoneCode defines model for PhoneCode.
type PhoneCode struct {
	// Countryid Country id (Can be mapped against countries.id)
	Countryid *int `json:"countryid,omitempty"`

	// Name Country name
	Name *string `json:"name,omitempty"`

	// Phonecode Area phone code
	Phonecode *string `json:"phonecode,omitempty"`
}

// References defines model for References.
type References struct {
	Countries       *[]Country        `json:"countries,omitempty"`
	Datetimeformats *[]DateTimeFormat `json:"datetimeformats,omitempty"`
	Numberformats   *[]NumberFormat   `json:"numberformats,omitempty"`
	Phonecodes      *[]PhoneCode      `json:"phonecodes,omitempty"`
	Regions         *[]Region         `json:"regions,omitempty"`
	Timezones       *[]Timezone       `json:"timezones,omitempty"`
}

// Region defines model for Region.
type Region struct {
	// Countryid Corresponding country identifier
	Countryid *int `json:"countryid,omitempty"`

	// Datetimeformatid Corresponding datetimeformat identifier
	Datetimeformatid *int `json:"datetimeformatid,omitempty"`

	// Description Region description
	Description *string `json:"description,omitempty"`

	// Id Region identifier
	Id *int `json:"id,omitempty"`

	// Numberformatid Corresponding numberformat identifier
	Numberformatid *int `json:"numberformatid,omitempty"`

	// Timezoneid Corresponding timezon identifier
	Timezoneid *int `json:"timezoneid,omitempty"`
}

// Timezone defines model for Timezone.
type Timezone struct {
	// Description Time zone description
	Description *string `json:"description,omitempty"`

	// Id Time zone identifier
	Id *int `json:"id,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetReference request
	GetReference(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetReference(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReferenceRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetReferenceRequest generates requests for GetReference
func NewGetReferenceRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reference")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetReferenceWithResponse request
	GetReferenceWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetReferenceResponse, error)
}

type GetReferenceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *References
}

// Status returns HTTPResponse.Status
func (r GetReferenceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReferenceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetReferenceWithResponse request returning *GetReferenceResponse
func (c *ClientWithResponses) GetReferenceWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetReferenceResponse, error) {
	rsp, err := c.GetReference(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReferenceResponse(rsp)
}

// ParseGetReferenceResponse parses an HTTP response from a GetReferenceWithResponse call
func ParseGetReferenceResponse(rsp *http.Response) (*GetReferenceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReferenceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest References
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
