/*
Pingdom Public API

Testing AnalysisAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_AnalysisAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AnalysisAPIService AnalysisCheckidAnalysisidGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var checkid int32
		var analysisid int32

		httpRes, err := apiClient.AnalysisAPI.AnalysisCheckidAnalysisidGet(context.Background(), checkid, analysisid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AnalysisAPIService AnalysisCheckidGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var checkid int32

		resp, httpRes, err := apiClient.AnalysisAPI.AnalysisCheckidGet(context.Background(), checkid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
